name: pytest

on:
  push:
    branches:
      - 'dev*'
  pull_request:
    branches:
      - main

jobs:
  pytest_push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.base_ref == ''

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "**/uv.lock"

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Run tests
        run: uv run python -m pytest -v --cov ${{ github.workspace }}/tests/
      
      - name: Pylint
        run: |
          cd ${{ github.workspace }}
          uv run black --check .
          uv run isort . --check-only
          uv run pylint AutoCarver --fail-under=9
          uv run flake8 AutoCarver

  pytest_pull:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13']

    defaults:
      run:
        shell: bash

    runs-on: ${{ matrix.os }}
    if: ${{ github.event_name == 'pull_request' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "**/uv.lock"
  
      - name: Install dependencies
        run: uv sync --all-extras

      - name: Run tests
        run: uv run python -m pytest -v --cov ${{ github.workspace }}/tests/
