name: pytest

on:
  push:
    branches:
      - 'dev*'
  pull_request:
    branches:
      - main

jobs:
  pytest_push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.base_ref == ''

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "**/uv.lock"

      - name: Install dependencies
        run: |
          uv lock --check
          uv sync --all-extras

      - name: Lint
        run: |
          uv run ruff check --output-format=github .
          uv run ruff format --check .
          uv run pylint AutoCarver --fail-under=9
          
      - name: Run tests
        run: uv run python -m pytest -v --cov tests/
      

  pytest_pull:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12']

    defaults:
      run:
        shell: bash

    runs-on: ${{ matrix.os }}
    if: ${{ github.event_name == 'pull_request' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "**/uv.lock"
  
      - name: Install dependencies
        run: |
          uv lock --check
          uv sync --all-extras

      - name: Lint
        run: |
          uv run ruff check --output-format=github .
          uv run ruff format --check .
          uv run pylint AutoCarver --fail-under=9

      - name: Run tests
        run: uv run python -m pytest -v --cov tests/
