name: Create Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    create-release:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: Extract Tag Name
          id: extract_tag_name
          run: |
            PR_TITLE="${{ github.event.pull_request.title }}"
            TAG_NAME=$(echo "$PR_TITLE" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
            echo "::set-output name=tag_name::$TAG_NAME"

        - name: Create Release
          uses: actions/create-release@v1
          with:
            tag_name: ${{ steps.extract_tag_name.outputs.tag_name }}
            release_name: Release ${{ steps.extract_tag_name.outputs.tag_name }}
            draft: false
            prerelease: false
            token: ${{ env.GITHUB_TOKEN }}
